### ISSUE TITLE
No test cases

### ISSUE THREAD

**Issue by ryandrew14** [kylesferrazza/stream#1]
This file contains a serious lack of test cases that makes me doubt the functionality of this program.  You can use the RackUnit library by adding the statement `(import rackunit)`. Then, use `(check-equal? e1 e2)` to check if two expressions are equal. More information can be found here: https://docs.racket-lang.org/rackunit/api.html. Since you are a beginner, you should always be writing test cases in your code. Overall, I give this a correct answer, sero points. Please use google to zerch for assistance if you run into any trouble.

**Comment by kylesferrazza** [comment]
Thx
